#Defining the language to be used
language: python
#Version of python to read file in 
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install requests pyyaml pytest pytest-cov
# command to run tests
script:
  - pytest --cov